site_name: equinox_vision
site_description: Vision models with equinox
site_author: Ryuichiro Hataya
site_url: https://mosko.tokyo/equinox_vision
repo_name: moskomule/equinox_vision
repo_url: https://github.com/moskomule/equinox_vision
edit_uri: blob/main/docs

theme:
  name: material

  features:
    - content.code.annotate

markdown_extensions:
  # mathjax
  - pymdownx.arithmatex:
      generic: true

  # syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: false
            members_order: source
            heading_level: 4

nav:
  - Home: 'index.md'